"=============================================================================
" .vimrc --- Config Entry file for Vim(8)
" => Yang Yang
"=============================================================================

" Note: Skip initialization for vim-tiny or vim-small.
if !1 | finish | endif

execute 'source' fnamemodify(expand('<sfile>'), ':h').'/rc/vimrc'
