#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings

yabai -m config window_origin_display default
yabai -m config window_placement second_child

# floating windows are always on top (default: off)
yabai -m config window_topmost on
yabai -m config window_shadow on
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.90
yabai -m config window_border off
yabai -m config window_border_width 6
yabai -m config active_window_border_color 0xff775759
yabai -m config normal_window_border_color 0xff555555
yabai -m config insert_feedback_color 0xffd75f5f
yabai -m config split_ratio 0.50
yabai -m config auto_balance off

# Mouse
yabai -m config mouse_modifier ctrl
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
# yabai -m config mouse_drop_action swap
# yabai -m config mouse_follows_focus on
# yabai -m config focus_follows_mouse autoraise

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 06

# Rules
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^Dictionary$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^Postlab$" manage=off
yabai -m rule --add app="^Simulator$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^システム環境設定$" manage=off
yabai -m rule --add app="^Electron$" manage=off
yabai -m rule --add app="^Parallels Desktop$" manage=off
yabai -m rule --add app="^FortiClient$" manage=off
yabai -m rule --add app="^TencentMeeting$" manage=off
yabai -m rule --add app="^WeChat$" manage=off
yabai -m rule --add app="^QQ$" manage=off
yabai -m rule --add app="^カレンダー$" manage=off
yabai -m rule --add app="^Slack$" manage=off
yabai -m rule --add app="^Karabiner.*$" manage=off
yabai -m rule --add app="^スティッキーズ$" manage=off
yabai -m rule --add app="^アクティビティモニタ$" manage=off

echo "yabai configuration loaded.."

# kill any existing limelight process if one exists, before we launch a new one
killall limelight &>/dev/null
limelight &>/dev/null &
