#!/usr/bin/env sh

# 1. Scripting Addition (SIPを一部無効化している場合のみ有効)
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

PADDING=6

# # global settings
# yabai -m config \
#   mouse_follows_focus off \
#   focus_follows_mouse off \
#   window_origin_display default \
#   window_placement second_child \
#   window_zoom_persist on \
#   window_shadow off \
#   window_opacity_duration 0.0 \
#   active_window_opacity 1.0 \
#   normal_window_opacity 0.90 \
#   window_opacity off \
#   insert_feedback_color 0xffd75f5f \
#   split_ratio 0.50 \
#   split_type auto \
#   auto_balance off \
#   top_padding "$PADDING" \
#   bottom_padding "$PADDING" \
#   left_padding "$PADDING" \
#   right_padding "$PADDING" \
#   window_gap 04 \
#   layout bsp \
#   mouse_modifier fn \
#   mouse_action1 move \
#   mouse_action2 resize \
#   mouse_drop_action swap

# 2. Global Settings
yabai -m config \
  mouse_follows_focus off \
  focus_follows_mouse off \
  window_origin_display focused \
  window_placement second_child \
  window_zoom_persist on \
  window_shadow off \
  window_animation_duration 0.0 \
  active_window_opacity 1.0 \
  normal_window_opacity 0.90 \
  window_opacity on \
  window_border on \
  window_border_width 2 \
  active_window_border_color 0xff77aaee \
  insert_feedback_color 0xffd75f5f \
  split_ratio 0.50 \
  auto_balance off \
  top_padding $PADDING \
  bottom_padding $PADDING \
  left_padding $PADDING \
  right_padding $PADDING \
  window_gap 6 \
  layout bsp \
  mouse_modifier alt \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap

# Mouse
# yabai -m config mouse_modifier ctrl
# yabai -m config mouse_action1 move
# yabai -m config mouse_action2 resize
# yabai -m config mouse_drop_action swap
# yabai -m config mouse_follows_focus on
# yabai -m config focus_follows_mouse autoraise

# yabai -m config top_padding "$PADDING"
# yabai -m config bottom_padding "$PADDING"
# yabai -m config left_padding "$PADDING"
# yabai -m config right_padding "$PADDING"
# yabai -m config window_gap 06

# 3. Floating Rules (タイル化させないアプリ)
yabai -m rule --add app="FortiClient" manage=off
yabai -m rule --add app="Nexitally" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Digital Colou?r Meter$" sticky=on manage=off

# float every app except for belows.
# yabai -m rule --add app!="^(kitty|Google Chrome)$" manage=off

echo "yabai configuration loaded.."
