hook_add = '''
" let g:php_folding = 1
'''

[ftplugin]
# why not working ?
_ = '''
  setlocal foldmethod=indent
'''

python = 'setlocal foldmethod=indent'

toml = 'syntax sync minlines=500'

help = '''
setlocal iskeyword+=:
setlocal iskeyword+=#
setlocal iskeyword+=-
'''

vim = '''
setlocal foldmethod=marker
'''
