# Non lazy load plugins

[[plugins]]
repo = 'Shougo/denite.nvim'
merge = 0

[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
build = 'yarn install'

[[plugins]]
repo = 'neoclide/coc-denite'

[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
  command! DeinRecache call dein#recache_runtimepath()
  command! DeinCleanUp call map(dein#check_clean(), "delete(v:val, 'rf')")
'''

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'mhinz/vim-startify'
hook_add = '''
  " autocmd User Startified doautocmd ColorScheme
  autocmd User Startified for key in ['b','s','t','v'] | exe 'nunmap <buffer>' key | endfor
  " let g:startify_change_to_dir       = 1
  let g:startify_change_to_vcs_root  = 1
  let g:startify_update_oldfiles     = 1
  let g:startify_fortune_use_unicode = 1
  " let g:startify_custom_header =
  "       \ map(split(system('fortune | cowsay -f dragon-and-cow'), '\n'), '"   ". v:val')
  let g:startify_lists = [
        \ { 'type': 'dir',       'header': ['    MRU '. getcwd()] },
        \ { 'type': 'files',     'header': ['    MRU']            },
        \ { 'type': 'bookmarks', 'header': ['    BOOKMARKS']      },
        \ { 'type': 'commands',  'header': ['   גּ COMMANDS']       },
        \ ]
  let g:startify_bookmarks = [
          \ { 'tc': '~/.tmux.conf' },
          \ { 'de':  g:dein#install_log_filename },
          \ ]
  let g:startify_commands = [
      \ { 'c1': ['Vim Reference', 'h ref'] },
      \ { 'c2': ['Vim CheckHealth', 'CheckHealth'] },
      \ { 'c3': ['Dein recache rtp', 'call dein#recache_runtimepath()'] },
      \ { 'c4': ['Update plugins', 'call dein#update()'] },
      \ ]
  let g:startify_skiplist = [
      \ 'COMMIT_EDITMSG',
      \ 'runtime/doc/.*\.txt',
      \ 'bundle/.*/doc/.*\.txt',
      \ 'plugged/.*/doc/.*\.txt',
      \ 'dein/doc/.*\.txt',
      \ escape(fnamemodify(resolve($VIMRUNTIME), ':p'), '\') .'doc/.*\.txt',
      \ ]

  if get(g:, 'enable_patched_font', 0)
    function! StartifyEntryFormat()
      return 'WebDevIconsGetFileTypeSymbol(absolute_path) ." ". entry_path'
    endfunction
  endif

  nnoremap <silent> <Leader>S :Startify<CR>
'''

[[plugins]]
repo = 'nixprime/cpsm'
merge = 0
build = 'sh -c "PY3=ON ./install.sh"'

[[plugins]]
on_if = "get(g:, 'enable_patched_font', 0)"
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  if get(g:, 'enable_patched_font', 0)
    let g:airline_powerline_fonts=1
    " let g:airline_left_sep=''
    " let g:airline_right_sep=''
  endif
  " let g:airline_left_sep = ' '
  " let g:airline_left_alt_sep = '|'
  " let g:airline_right_sep = ' '
  " let g:airline_right_alt_sep = '|'

  let g:airline_skip_empty_sections = 1
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#hunks#enabled = 1
  let g:airline#extensions#ale#enabled = 1
  let g:airline#extensions#fugitiveline#enabled = 1

  let g:airline#extensions#tabline#show_tab_nr = 1
  let g:airline#extensions#tabline#tab_nr_type= 2
  let g:airline#extensions#tabline#show_tab_type = 1
  let g:airline#extensions#tabline#buffers_label = '𝓑𝓤𝓕𝓕𝓔𝓡𝓢'
  let g:airline#extensions#tabline#tabs_label = '𝓣𝓐𝓑𝓢'

  let g:airline#extensions#tabline#buffer_idx_mode = 1
  let g:airline#extensions#tabline#buffer_idx_format = {}

  " let g:airline_section_error = '%{airline#util#wrap(airline#extensions#coc#get_error(),0)}'
  " let g:airline_section_warning = '%{airline#util#wrap(airline#extensions#coc#get_warning(),0)}'

  let g:airline#extensions#ale#error_symbol = '✖ :'
  let g:airline#extensions#ale#warning_symbol = '⚠ :'
  let g:airline#extensions#ale#checking_symbol = 'checking...'
  for s:i in range(9)
    call extend(g:airline#extensions#tabline#buffer_idx_format,
          \ {s:i : kiooss#api#import('messletters').bubble_num(s:i, 1). ' '})
  endfor
  unlet s:i
  nmap <leader>1 <Plug>AirlineSelectTab1
  nmap <leader>2 <Plug>AirlineSelectTab2
  nmap <leader>3 <Plug>AirlineSelectTab3
  nmap <leader>4 <Plug>AirlineSelectTab4
  nmap <leader>5 <Plug>AirlineSelectTab5
  nmap <leader>6 <Plug>AirlineSelectTab6
  nmap <leader>7 <Plug>AirlineSelectTab7
  nmap <leader>8 <Plug>AirlineSelectTab8
  nmap <leader>9 <Plug>AirlineSelectTab9
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
hook_add = '''
  " let g:EditorConfig_verbose = 1
'''

[[plugins]]
repo = 'pbrisbin/vim-mkdir'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'Shougo/context_filetype.vim'
hook_add = '''
if !exists('g:context_filetype#same_filetypes')
  let g:context_filetype#same_filetypes = {}
endif
" In c buffers, completes from cpp and d buffers.
let g:context_filetype#same_filetypes.c = 'cpp,d'
" In cpp buffers, completes from c buffers.
let g:context_filetype#same_filetypes.cpp = 'c'
" In gitconfig buffers, completes from all buffers.
let g:context_filetype#same_filetypes.gitconfig = '_'
" In default, completes from all buffers.
let g:context_filetype#same_filetypes._ = '_'
'''
[[plugins]]
repo = 'roxma/nvim-yarp'
on_if = '!has("nvim")'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'

# [[plugins]]
# repo = 'Shougo/neco-syntax'

#### colors start
[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'ayu-theme/ayu-vim'

[[plugins]]
repo = 'lu-ren/SerialExperimentsLain'

[[plugins]]
repo = 'chriskempson/base16-vim'

[[plugins]]
repo = 'nightsense/vimspectr'

[[plugins]]
repo = 'rafi/awesome-vim-colorschemes'

[[plugins]]
repo = 'whatyouhide/vim-gotham'

[[plugins]]
repo = 'KeitaNakamura/neodark.vim'

[[plugins]]
repo = 'nightsense/snow'

[[plugins]]
repo = 'drewtempelmeyer/palenight.vim'
#### colors end

[[plugins]]
repo = 'benmills/vimux'
hook_add ='''
  " map <Leader>rb :<C-u>call VimuxRunCommand("clear; date")<CR>

  " Prompt for a command to run
  map <Leader>vp :VimuxPromptCommand<CR>

  " Run last command executed by VimuxRunCommand
  " map <Leader>vl :VimuxRunLastCommand<CR>

  " Inspect runner pane
  " map <Leader>vi :VimuxInspectRunner<CR>

  " Close vim tmux runner opened by VimuxRunCommand
  map <Leader>vq :VimuxCloseRunner<CR>

  " Interrupt any command running in the runner pane
  " map <Leader>vx :VimuxInterruptRunner<CR>

  " Zoom the runner pane (use <bind-key> z to restore runner pane)
  map <Leader>vz :call VimuxZoomRunner()<CR>
'''

[[plugins]]
repo = 'gregsexton/MatchTag'

# [[plugins]]
# repo = 'Yggdroot/indentLine'
# hook_add = '''
#   " let g:indentLine_char = '│'
#   " let g:indentLine_first_char = ''
#   " let g:indentLine_showFirstIndentLevel = 1
#   " let g:indentLine_setColors = 0
#   let g:indentLine_fileTypeExclude = ['startify']

#   nnoremap <silent> <leader>\ :<C-u>IndentLinesToggle<CR>
# '''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  if get(g:, 'enable_patched_font', 0)
    let g:gitgutter_sign_added = ''
    let g:gitgutter_sign_modified = ''
    let g:gitgutter_sign_removed = ''
    let g:gitgutter_sign_modified_removed = ''
  endif
'''

[[plugins]]
repo = 'chemzqm/vim-jsx-improve'

[[plugins]]
repo = 'vim-scripts/jQuery'

# [[plugins]]
# repo = 'pangloss/vim-javascript'

# [[plugins]]
# repo = 'MaxMEllon/vim-jsx-pretty'

# [[plugins]]
# repo = 'mxw/vim-jsx'
# hook_add = '''
# let g:jsx_ext_required = 0
# '''

[[plugins]]
repo = 'alvan/vim-closetag'
hook_add ='''
let g:closetag_filenames = "*.html,*.xhtml,*.phtml,*.php,*.jsx,*.js"
'''

# [[plugins]]
# repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-git'

[[plugins]]
repo = 'tpope/vim-haml'

[[plugins]]
repo = 'tpope/vim-markdown'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-surround'
hook_add = '''
  let g:surround_no_insert_mappings = 1
'''

[[plugins]]
repo = 'tpope/vim-unimpaired'

[[plugins]]
repo = 'tpope/vim-eunuch'

[[plugins]]
repo = 'tpope/vim-dispatch'

# text object plugins {{{
[[plugins]]
repo = 'wellle/targets.vim'

[[plugins]]
repo = 'junegunn/vim-after-object'
hook_add = '''
  autocmd VimEnter * call after_object#enable('=', ':', '-', '#', ' ')
'''

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-function'

[[plugins]]
repo = 'kana/vim-textobj-entire'

[[plugins]]
repo = 'thalesmello/vim-textobj-methodcall'

[[plugins]]
repo = 'rhysd/vim-textobj-anyblock'

[[plugins]]
repo = 'nelstrom/vim-textobj-rubyblock'
# }}}

# [[plugins]]
# repo = 'sickill/vim-pasta'

# snippets {{{
[[plugins]]
repo = 'SirVer/ultisnips'
hook_add = '''
  let g:UltiSnipsExpandTrigger="<c-k>"
  let g:UltiSnipsJumpForwardTrigger="<c-k>"
  let g:UltiSnipsJumpBackwardTrigger="<c-j>"
  " If you want :UltiSnipsEdit to split your window.
  let g:UltiSnipsEditSplit="vertical"

  " make vim recognizing snippets dir
  " use different snippets dir
  let g:UltiSnipsSnippetsDir='~/.vim/UltiSnips/'
  " let g:UltiSnipsSnippetDirectories=["UltiSnips"]
'''

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'algotech/ultisnips-php'

[[plugins]]
repo = 'epilande/vim-react-snippets'
# }}}

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
hook_add = '''
  let g:better_whitespace_operator='_s'
'''

[[plugins]]
repo = 'kiooss/vim-zenkaku-space'

# [[plugins]]
# repo = 'jiangmiao/auto-pairs'

# [[plugins]]
# repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_set_quickfix = 1
  let g:ale_lint_delay = 1500
  let g:ale_lint_on_text_changed = 0
  let g:ale_lint_on_enter = 1
  let g:ale_lint_on_save = 1
  let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
  let g:ale_vim_vint_show_style_issues = 0

  let g:ale_linter_aliases = {
        \   'javascript.jsx': 'javascript',
        \   'jsx': 'javascript'
        \}

  let g:ale_linters = {
        \   'php': ['php'],
        \   'javascript': ['eslint'],
        \   'typescript': ['tslint', 'tsserver'],
        \   'ruby': [],
        \}
  let g:ale_fixers = {
        \ 'javascript': ['eslint', 'standard'],
        \ 'typescript': ['tslint'],
        \ 'json': ['fixjson'],
        \ 'ruby': ['rubocop', 'prettier']
        \}

  let g:ale_pattern_options = {
        \ '\.min\.js$': {'ale_linters': [], 'ale_fixers': []},
        \ '\.min\.css$': {'ale_linters': [], 'ale_fixers': []},
        \}

  let g:ale_sign_error = '✖'
  let g:ale_sign_warning = '⚠'
  let g:ale_sign_info = 'ℹ'
  let g:ale_sign_style_error = '>>'
  let g:ale_sign_style_warning = '--'

  if get(g:, 'enable_patched_font', 0)
    let g:ale_statusline_format = ['✖ %d', '⚠ %d', '⬥ ok']
  endif

  nmap <silent> <C-k> <Plug>(ale_previous_wrap)
  nmap <silent> <C-j> <Plug>(ale_next_wrap)
  nmap <localleader>j <Plug>(ale_fix)
  nmap <localleader>d <Plug>(ale_detail)
'''

[[plugins]]
repo = 'nelsyeung/twig.vim'

[[plugins]]
repo = 'AndrewRadev/switch.vim'

[[plugins]]
repo = 'chrisbra/vim-zsh'

[[plugins]]
repo = 'ujihisa/neco-look'

[[plugins]]
repo = 'airblade/vim-rooter'
hook_add = '''
  let g:rooter_silent_chdir = 1
  let g:rooter_patterns = [
    \ 'Rakefile',
    \ 'Gemfile',
    \ 'composer.json',
    \ '.git',
    \ '.git/',
    \ '_darcs/',
    \ '.hg/',
    \ '.bzr/',
    \ '.svn/'
    \ ]
'''

[[plugins]]
repo = 'StanAngeloff/php.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'othree/html5.vim'

# [[plugins]]
# repo = 'docteurklein/php-getter-setter.vim'

[[plugins]]
repo = 'groenewege/vim-less'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'

[[plugins]]
repo = 'ternjs/tern_for_vim'
build = 'npm install'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'tmux-plugins/vim-tmux'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'neoclide/jsonc.vim'

# [[plugins]]
# repo = 'neoclide/vim-easygit'

# [[plugins]]
# repo = 'neoclide/denite-git'

[[plugins]]
repo = 'wincent/vim-clipper'
hook_add = '''
let g:ClipperAddress='~/.clipper.sock'
let g:ClipperPort=0
'''

[[plugins]]
repo = 'justinmk/vim-sneak'
hook_add = '''
  map f <Plug>Sneak_s
  map F <Plug>Sneak_S
  let g:sneak#label = 1
  let g:sneak#use_ic_scs = 1
  let g:sneak#absolute_dir = 1
'''

[[plugins]]
repo = 'justinmk/vim-dirvish'

[[plugins]]
repo = 'justinmk/vim-gtfo'

[[plugins]]
repo = 'sunaku/vim-dasht'
on_if = 'executable("dasht")'
hook_add = '''
  nnoremap <silent> gK :call Dasht([expand('<cword>'), expand('<cWORD>')])<CR>
  vnoremap <silent> gK y:<C-U>call Dasht(getreg(0))<Return>
  let g:dasht_filetype_docsets = {}
  let g:dasht_filetype_docsets['ruby'] = ['Ruby_on_Rails*']
  let g:dasht_filetype_docsets['haml'] = ['Ruby_on_Rails*']
  let g:dasht_filetype_docsets['php'] = ['Symfony']
'''

[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'

[[plugins]]
repo = 'junegunn/vim-peekaboo'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'chr4/nginx.vim'

[[plugins]]
repo = 'christianrondeau/vim-base64'

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'

[[plugins]]
repo = 'tobyS/vmustache'

[[plugins]]
repo = 'machakann/vim-highlightedyank'

[[plugins]]
repo = 'mattn/vim-sqlfmt'
#  vim: set ts=2 sw=2 tw=80 et :
