hook_add = '''
  let g:php_folding = 0
'''

[ftplugin]
python = 'setlocal foldmethod=indent'

toml = 'syntax sync minlines=500'

help = '''
setlocal iskeyword+=:
setlocal iskeyword+=#
setlocal iskeyword+=-
'''

vim = '''
setlocal foldmethod=marker
'''
