[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
on_source = ['unite.vim', 'vimshell.vim']

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
depends = ['neomru.vim']
hook_source = 'source ~/.vim/rc/plugins/denite.rc.vim'
hook_add = 'call kiooss#mappings#denite()'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_event = 'InsertEnter'
hook_source = '''
let g:deoplete#enable_at_startup = 1
source ~/.vim/rc/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/echodoc.vim'
on_event = 'CompleteDone'
hook_source = '''
" let g:echodoc#type = 'signature'
call echodoc#enable()
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
on_cmd = 'IndentLinesToggle'
hook_add = '''
  nnoremap <silent> <leader>\ :<C-u>IndentLinesToggle<CR>
'''

[[plugins]]
repo = 'godlygeek/tabular'
on_cmd = 'Tabularize'
hook_add = '''
  nnoremap <Leader>= :Tabularize /=>\?<CR>
  vnoremap <Leader>= :Tabularize /=>\?<CR>
  nnoremap <Leader>: :Tabularize /:\zs<CR>
  vnoremap <Leader>: :Tabularize /:\zs<CR>
'''

[[plugins]]
repo = 'lvht/phpcd.vim'
on_ft = 'php'
build = 'composer install'

# [[plugins]]
# repo = 'shawncplus/phpcomplete.vim'
# on_ft = 'php'

# [[plugins]]
# repo = 'stephpy/vim-php-cs-fixer'
# on_ft = 'php'

# [[plugins]]
# repo = 'swekaj/php-foldexpr.vim'
# on_ft = 'php'

[[plugins]]
repo = 'arnaud-lb/vim-php-namespace'
on_ft = ['php', 'yaml']
hook_add = '''
  let g:php_namespace_sort_after_insert = 1
  function! IPhpInsertUse()
      call PhpInsertUse()
      call feedkeys('a',  'n')
  endfunction
  " autocmd FileType php inoremap <Leader>u <Esc>:call IPhpInsertUse()<CR>
  autocmd FileType php noremap <Leader>u :call PhpInsertUse()<CR>

  function! IPhpExpandClass()
      call PhpExpandClass()
      call feedkeys('a', 'n')
  endfunction
  " autocmd FileType php inoremap <Leader>e <Esc>:call IPhpExpandClass()<CR>
  autocmd FileType php noremap <Leader>e :call PhpExpandClass()<CR>

  " autocmd FileType php inoremap <Leader>s <Esc>:call PhpSortUse()<CR>
  autocmd FileType php noremap <Leader>s :call PhpSortUse()<CR>
'''

# [[plugins]]
# repo = 'qbbr/vim-symfony'
# on_ft = 'php'

# [[plugins]]
# repo = 'tobyS/vmustache'
# on_ft = 'php'
#
# [[plugins]]
# repo = 'tobyS/pdv'
# on_ft = 'php'
# depends = 'tobyS/vmustache'
# hook_add = '''
#   let g:pdv_template_dir = $HOME ."/.vim/plugged/pdv/templates_snip"
#   nnoremap <Leader>doc :call pdv#DocumentWithSnip()<CR>
# '''

# [[plugins]]
# repo = 'adoy/vim-php-refactoring-toolbox'
# on_ft = 'php'

[[plugins]]
repo = 'ecomba/vim-ruby-refactoring'
on_ft = 'ruby'

# [[plugins]]
# repo = 'tsaleh/vim-shoulda'
# on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = 'ruby'

[[plugins]]
repo = 'chrisbra/csv.vim'
on_ft = 'csv'

[[plugins]]
repo = 'osyo-manga/vim-precious'
on_ft = 'toml'

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'vim-scripts/BufOnly.vim'
on_cmd = ['Bonly', 'BufOnly']

[[plugins]]
repo = 'Shougo/deol.nvim'
on_cmd = ['Deol', 'DeolEdit', 'DeolCd']

[[plugins]]
repo = 'junegunn/gv.vim'
on_cmd = ['GV']

[[plugins]]
repo = 'lambdalisue/gina.vim'
on_cmd = ['Gina']
