# NOTE: the plugins bdon't have plugin directroy do not need dein lazy load mechanism.

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
on_source = ['unite.vim', 'vimshell.vim']

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_if = 1
on_event = 'TextYankPost'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
depends = ['neomru.vim']
hook_source = "call zvim#util#source_rc('plugins/denite.rc.vim')"
hook_add = 'call kiooss#mappings#denite#init()'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_event = 'InsertEnter'
hook_source = "call zvim#util#source_rc('plugins/deoplete.rc.vim')"

[[plugins]]
repo = 'Shougo/echodoc.vim'
on_event = 'CompleteDone'
hook_source = '''
" let g:echodoc#type = 'signature'
call echodoc#enable()
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTreeToggle', 'NERDTreeFind', 'NERDTree']
hook_add = '''
  " close NERDTree after a file is opened
  let NERDTreeQuitOnOpen=0
  " show hidden files in NERDTree
  let NERDTreeShowHidden=1
  " remove some files by extension
  let NERDTreeIgnore = ['\.js.map$', '\~$', '\.o$[[file]]', '\.git$']
  " Toggle NERDTree
  nnoremap <silent> <Leader>nt :NERDTreeToggle<CR>
  nnoremap <silent> <Leader>nf :NERDTreeFind<CR>
  " expand to the path of the file in the current buffer
  " nnoremap <expr><silent> <leader>nf g:NERDTree.IsOpen() ?
  "       \ ":NERDTreeClose<CR>" : ":NERDTreeFind<CR>"
  " open NERDTree automatically when vim starts up on opening a directory
  autocmd StdinReadPre * let s:std_in=1
  autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) &&
        \ !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif
  " close vim if the only window left open is a NERDTree
  autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") &&
        \ b:NERDTree.isTabTree()) | q | endif
'''

[[plugins]]
repo = 'majutsushi/tagbar'
on_cmd = 'TarbarToggle'
hook_add = '''
  nnoremap <silent> <Leader>t :TagbarToggle<CR>
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
on_cmd = 'IndentLinesToggle'
hook_add = '''
  nnoremap <silent> <leader>\ :<C-u>IndentLinesToggle<CR>
'''

[[plugins]]
repo = 'godlygeek/tabular'
on_cmd = 'Tabularize'
hook_add = '''
  nnoremap <Leader>= :Tabularize /=>\?<CR>
  vnoremap <Leader>= :Tabularize /=>\?<CR>
  nnoremap <Leader>: :Tabularize /:\zs<CR>
  vnoremap <Leader>: :Tabularize /:\zs<CR>
'''

[[plugins]]
repo = 'lvht/phpcd.vim'
on_ft = 'php'
build = 'composer install'

# [[plugins]]
# repo = 'shawncplus/phpcomplete.vim'
# on_ft = 'php'

# [[plugins]]
# repo = 'stephpy/vim-php-cs-fixer'
# on_ft = 'php'

# [[plugins]]
# repo = 'swekaj/php-foldexpr.vim'
# on_ft = 'php'

[[plugins]]
repo = 'arnaud-lb/vim-php-namespace'
on_ft = ['php', 'yaml']
hook_add = '''
  let g:php_namespace_sort_after_insert = 1
  function! IPhpInsertUse()
      call PhpInsertUse()
      call feedkeys('a',  'n')
  endfunction
  " autocmd FileType php inoremap <Leader>u <Esc>:call IPhpInsertUse()<CR>
  autocmd FileType php noremap <Leader>u :call PhpInsertUse()<CR>

  function! IPhpExpandClass()
      call PhpExpandClass()
      call feedkeys('a', 'n')
  endfunction
  " autocmd FileType php inoremap <Leader>e <Esc>:call IPhpExpandClass()<CR>
  autocmd FileType php noremap <Leader>e :call PhpExpandClass()<CR>

  " autocmd FileType php inoremap <Leader>s <Esc>:call PhpSortUse()<CR>
  autocmd FileType php noremap <Leader>s :call PhpSortUse()<CR>
'''

# [[plugins]]
# repo = 'qbbr/vim-symfony'
# on_ft = 'php'

# [[plugins]]
# repo = 'tobyS/vmustache'
# on_ft = 'php'
#
# [[plugins]]
# repo = 'tobyS/pdv'
# on_ft = 'php'
# depends = 'tobyS/vmustache'
# hook_add = '''
#   let g:pdv_template_dir = $HOME ."/.vim/plugged/pdv/templates_snip"
#   nnoremap <Leader>doc :call pdv#DocumentWithSnip()<CR>
# '''

# [[plugins]]
# repo = 'adoy/vim-php-refactoring-toolbox'
# on_ft = 'php'

# [[plugins]]
# repo = 'ecomba/vim-ruby-refactoring'
# on_ft = 'ruby'

# [[plugins]]
# repo = 'tsaleh/vim-shoulda'
# on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = 'ruby'

[[plugins]]
repo = 'chrisbra/csv.vim'
on_ft = 'csv'

[[plugins]]
repo = 'osyo-manga/vim-precious'
on_ft = 'toml'

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'vim-scripts/BufOnly.vim'
on_cmd = ['Bonly', 'BufOnly']

[[plugins]]
repo = 'Shougo/deol.nvim'
on_cmd = ['Deol', 'DeolEdit', 'DeolCd']

[[plugins]]
repo = 'junegunn/gv.vim'
on_cmd = ['GV', 'GV!']

[[plugins]]
repo = 'lambdalisue/gina.vim'
on_cmd = ['Gina']

[[plugins]]
repo = 'mbbill/undotree'
on_cmd = ['UndotreeToggle']
hook_add = '''
nnoremap U :UndotreeToggle<CR>
'''
