hook_add = '''
  let g:php_folding = 0
'''

[ftplugin]
python = 'setlocal foldmethod=indent'

toml = 'syntax sync minlines=500'

help = '''
setlocal iskeyword+=:
setlocal iskeyword+=#
setlocal iskeyword+=-
'''

vim = '''
setlocal foldmethod=marker
'''

ruby = '''
setlocal iskeyword+=!
setlocal iskeyword+=?

" let g:rubycomplete_buffer_loading = 1
" let g:rubycomplete_classes_in_global = 1
" let g:rubycomplete_rails = 1
" let g:rubycomplete_load_gemfile = 1
'''
