[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
on_source = ['unite.vim', 'vimshell.vim']

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
depends = ['neomru.vim']
hook_source = 'source ~/.vim/rc/plugins/denite.rc.vim'
hook_add = '''
  nnoremap <LocalLeader>c :<C-u>Denite colorscheme -auto-preview<CR>
  nnoremap <LocalLeader>ft :<C-u>Denite filetype -highlight-mode-insert=Search<CR>
  nnoremap <LocalLeader>h :<C-u>Denite help<CR>
  nnoremap <silent> <leader>f  :<C-u>Denite file_rec/git -highlight-mode-insert=Search<CR>
  " nnoremap <silent> <leader>r  :<C-u>Denite register -mode=normal -highlight-mode-insert=Search<CR>
  nnoremap <silent> <leader>ol :<C-u>Denite outline -highlight-mode-insert=Search<CR>
  nnoremap <silent> <leader>ls :<C-u>Denite buffer<CR>
  nnoremap <silent> <leader>m :<C-u>Denite file_mru -highlight-mode-insert=Search<CR>
  nnoremap <silent> <Leader>r
        \ :<C-u>Denite -mode=normal -buffer-name=register
        \ -highlight-mode-insert=Search register<CR>
  xnoremap <silent> <Leader>r
        \ :<C-u>Denite -mode=normal -default-action=replace -buffer-name=register
        \ -highlight-mode-insert=Search register<CR>
  nnoremap <silent> <LocalLeader>v
        \ :<C-u>Denite file_rec:~/.vim -highlight-mode-insert=Search<CR>
  nnoremap <silent> <LocalLeader>d
        \ :<C-u>Denite file_rec:~/.dotfiles -highlight-mode-insert=Search<CR>
  nnoremap <silent> / :<C-u>Denite -buffer-name=search
        \ -highlight-mode-insert=Search line<CR>
  nnoremap <silent> * :<C-u>DeniteCursorWord -buffer-name=search
        \ -mode=normal line<CR>
  nnoremap <silent> # :<C-u>DeniteCursorWord -buffer-name=search
        \ -no-empty -mode=normal grep/git<CR>
  nnoremap <silent> <leader>s :<C-u>Denite file_point file_old
        \ `finddir('.git', ';') != '' ? 'file_rec/git' : 'file_rec'`<CR>
  nnoremap <silent><expr> tt  &filetype == 'help' ?  "g\<C-]>" :
        \ ":\<C-u>DeniteCursorWord -buffer-name=tag -immediately
        \  tag:include\<CR>"
  " nnoremap <silent><expr> ;t :<C-u>DeniteCursorWord --buffer-name=tag
  "       \ tag:include<CR>
  nnoremap <silent><expr> tp  &filetype == 'help' ?
        \ ":\<C-u>pop\<CR>" : ":\<C-u>Denite -mode=normal jump\<CR>"
  " nnoremap <silent> [Window]n :<C-u>Denite dein<CR>
  nnoremap <silent> <leader>ag :<C-u>Denite -buffer-name=search
        \ -no-empty -mode=normal grep<CR>
  nnoremap <silent> <leader>gg :<C-u>Denite -buffer-name=search
        \ -no-empty -mode=normal grep/git<CR>
  nnoremap <silent> <leader>st :<C-u>Denite -buffer-name=search
        \ -no-empty -mode=normal gitstatus<CR>
  nnoremap <silent> n :<C-u>Denite -buffer-name=search
        \ -resume -mode=normal -refresh<CR>
  " nnoremap <silent> <C-t> :<C-u>Denite
  "       \ -select=`tabpagenr()-1` -mode=normal deol<CR>
  " nnoremap <silent> <C-k> :<C-u>Denite -mode=normal change jump<CR>
  nnoremap <silent> <leader>gl :<C-u>Denite -buffer-name=search
        \ -no-empty -mode=normal gitlog<CR>
  nnoremap <silent> <leader>gs :<C-u>Denite -mode=normal gitstatus<CR>
  " nnoremap <silent> ;;
  "       \ :<C-u>Denite command command_history<CR>
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_event = 'InsertEnter'
hook_source = '''
let g:deoplete#enable_at_startup = 1
source ~/.vim/rc/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
on_cmd = 'IndentLinesToggle'
hook_add = '''
  nnoremap <silent> <leader>\ :<C-u>IndentLinesToggle<CR>
'''

[[plugins]]
repo = 'godlygeek/tabular'
on_cmd = 'Tabularize'
hook_add = '''
  nnoremap <Leader>= :Tabularize /=>\?<CR>
  vnoremap <Leader>= :Tabularize /=>\?<CR>
  nnoremap <Leader>: :Tabularize /:\zs<CR>
  vnoremap <Leader>: :Tabularize /:\zs<CR>
'''

[[plugins]]
repo = 'lvht/phpcd.vim'
on_ft = 'php'
build = 'composer install'

# [[plugins]]
# repo = 'shawncplus/phpcomplete.vim'
# on_ft = 'php'

# [[plugins]]
# repo = 'stephpy/vim-php-cs-fixer'
# on_ft = 'php'

# [[plugins]]
# repo = 'swekaj/php-foldexpr.vim'
# on_ft = 'php'

[[plugins]]
repo = 'arnaud-lb/vim-php-namespace'
on_ft = ['php', 'yaml']
hook_add = '''
  let g:php_namespace_sort_after_insert = 1
  function! IPhpInsertUse()
      call PhpInsertUse()
      call feedkeys('a',  'n')
  endfunction
  " autocmd FileType php inoremap <Leader>u <Esc>:call IPhpInsertUse()<CR>
  autocmd FileType php noremap <Leader>u :call PhpInsertUse()<CR>

  function! IPhpExpandClass()
      call PhpExpandClass()
      call feedkeys('a', 'n')
  endfunction
  " autocmd FileType php inoremap <Leader>e <Esc>:call IPhpExpandClass()<CR>
  autocmd FileType php noremap <Leader>e :call PhpExpandClass()<CR>

  " autocmd FileType php inoremap <Leader>s <Esc>:call PhpSortUse()<CR>
  autocmd FileType php noremap <Leader>s :call PhpSortUse()<CR>
'''

# [[plugins]]
# repo = 'qbbr/vim-symfony'
# on_ft = 'php'

# [[plugins]]
# repo = 'tobyS/vmustache'
# on_ft = 'php'
#
# [[plugins]]
# repo = 'tobyS/pdv'
# on_ft = 'php'
# depends = 'tobyS/vmustache'
# hook_add = '''
#   let g:pdv_template_dir = $HOME ."/.vim/plugged/pdv/templates_snip"
#   nnoremap <Leader>doc :call pdv#DocumentWithSnip()<CR>
# '''

# [[plugins]]
# repo = 'adoy/vim-php-refactoring-toolbox'
# on_ft = 'php'

[[plugins]]
repo = 'ecomba/vim-ruby-refactoring'
on_ft = 'ruby'

# [[plugins]]
# repo = 'tsaleh/vim-shoulda'
# on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = 'ruby'

[[plugins]]
repo = 'chrisbra/csv.vim'
on_ft = 'csv'

[[plugins]]
repo = 'osyo-manga/vim-precious'
on_ft = 'toml'

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'vim-scripts/BufOnly.vim'
on_cmd = ['Bonly', 'BufOnly']

[[plugins]]
repo = 'Shougo/deol.nvim'
on_cmd = ['Deol', 'DeolEdit', 'DeolCd']

[[plugins]]
repo = 'junegunn/gv.vim'
on_cmd = ['GV']

[[plugins]]
repo = 'lambdalisue/gina.vim'
on_cmd = ['Gina']
