#!/usr/bin/env ruby

require 'optparse'

options = {}

OptionParser.new do |opts|
  opts.banner = "Usage: example.rb [options]"

  options[:force] = false

  opts.on("-f", "--force", "Run forcely") do |v|
    options[:force] = true
  end
end.parse!

#https://github.com/madflow/vim-php.git
#https://github.com/kien/rainbow_parentheses.vim.git
#https://github.com/othree/html5.vim.git
#https://github.com/tsaleh/vim-tmux.git
#https://github.com/swekaj/php-foldexpr.vim.git
git_bundles = %w{
  https://github.com/vim-scripts/gtags.vim
  https://github.com/docteurklein/php-getter-setter.vim.git
  https://github.com/chrisbra/csv.vim.git
  https://github.com/mattn/emmet-vim.git
  https://github.com/gregsexton/MatchTag.git
  https://github.com/vim-scripts/taglist.vim
  https://github.com/pbrisbin/vim-mkdir.git
  https://github.com/edkolev/promptline.vim.git
  https://github.com/airblade/vim-gitgutter.git
  https://github.com/shawncplus/phpcomplete.vim.git
  https://github.com/vim-scripts/sudo.vim.git
  https://github.com/astashov/vim-ruby-debugger.git
  https://github.com/godlygeek/tabular.git
  https://github.com/pangloss/vim-javascript.git
  https://github.com/scrooloose/nerdtree.git
  https://github.com/timcharper/textile.vim.git
  https://github.com/tomtom/tcomment_vim.git
  https://github.com/tpope/vim-cucumber.git
  https://github.com/tpope/vim-endwise.git
  https://github.com/tpope/vim-fugitive.git
  https://github.com/tpope/vim-git.git
  https://github.com/tpope/vim-haml.git
  https://github.com/tpope/vim-markdown.git
  https://github.com/tpope/vim-rails.git
  https://github.com/tpope/vim-repeat.git
  https://github.com/tpope/vim-surround.git
  https://github.com/tpope/vim-vividchalk.git
  https://github.com/tsaleh/vim-shoulda.git
  https://github.com/vim-ruby/vim-ruby.git
  https://github.com/vim-scripts/Gist.vim.git
  https://github.com/vim-scripts/IndexedSearch.git
  https://github.com/vim-scripts/jQuery.git
  https://github.com/kana/vim-textobj-user.git
  https://github.com/nelstrom/vim-textobj-rubyblock.git
  https://github.com/jgdavey/vim-blockle.git
  https://github.com/Shougo/neocomplcache.git
  https://github.com/sickill/vim-pasta.git
  https://github.com/ecomba/vim-ruby-refactoring.git
  https://github.com/tomtom/tlib_vim.git
  https://github.com/MarcWeber/vim-addon-mw-utils.git
  https://github.com/garbas/vim-snipmate.git
  https://github.com/honza/vim-snippets
  https://github.com/evidens/vim-twig.git
  https://github.com/ervandew/supertab.git
  https://github.com/arnaud-lb/vim-php-namespace
  https://github.com/qbbr/vim-symfony
  https://github.com/editorconfig/editorconfig-vim.git
  https://github.com/mileszs/ack.vim
  https://github.com/kien/ctrlp.vim
  git://github.com/altercation/vim-colors-solarized.git
  https://github.com/kchmck/vim-coffee-script.git
  https://github.com/ntpeters/vim-better-whitespace.git
  https://github.com/nathanaelkane/vim-indent-guides
  https://github.com/morhetz/gruvbox.git
  https://github.com/sickill/vim-monokai.git
  https://github.com/bling/vim-airline.git
}
#https://github.com/scrooloose/snipmate-snippets.git
#https://github.com/tsaleh/vim-matchit.git

require 'fileutils'
require 'open-uri'

bundles_dir = File.expand_path File.join(File.dirname(__FILE__), "bundle")

if options[:force]
  FileUtils.rm_rf(bundles_dir)
  FileUtils.mkdir(bundles_dir)
  FileUtils.cd(bundles_dir)

  git_bundles.each do |url|
    puts url
    `git clone #{url}`
    #`git clone -q #{url}`
  end
else
  FileUtils.cd(bundles_dir)

  git_bundles.each do |url|
    bundle_name = File.basename(url, ".git")
    unless File.exists? File.join(bundles_dir, bundle_name)
      puts url
      `git clone #{url}`
    end
  end
end

#Dir["*/.git"].each {|f| FileUtils.rm_rf(f) }

