#!/usr/bin/env sh

limelight -m config width 2
# limelight -m config radius 10
# limelight -m config placement exterior
# limelight -m config active_color 0xFF40FF00
# limelight -m config normal_color 0x00FFFFFF
# limelight -m config active_color 0xFFBF616A
limelight -m config active_color 0xff24ccaa

echo "limelight configuration loaded.."
